### PR TITLE
changed how temp is read, added min/max to perf_data

### PR DESCRIPTION
**Pull request by sirtoobii**
First of all, thank you for this very useful plugin :+1: 

I've experienced some difficulties with permissions. I've also tried to add the `nagios` user to to `video` group, however this didn't work when running the command remotely (I'm using Icing2). 
Therefore I changed the method how the temperature is read to a more "robust" way which doesn't relay on a "third" command and special group memberships / permissions.

I've also adjusted the perf_data a bit to get these fancy graphs:
image

### CODE REVIEW

**Comment by Napsty** [comment]
Thx for the contribution @sirtoobii ! 
Good idea with reading `/sys/class/thermal/thermal_zone0/temp`, definitely better to not needing `sudo`. 
However I see a difference in the temperature when comparing `/sys/class/thermal/thermal_zone0/temp` and `/usr/bin/vcgencmd measure_temp`. 

```
pi@raspberrypi:~ $ echo $(( $(cat /sys/class/thermal/thermal_zone0/temp) / 1000 ))
40

pi@raspberrypi:~ $ /usr/bin/vcgencmd measure_temp
temp=41.3'C
```

Which one is true? I don't know. What are the readings on your Raspi? 
Maybe we can find out, what `/usr/bin/vcgencmd measure_temp` is reading to get another temperature reading.

**Comment by sirtoobii** [comment]
Ah yes...I forgot to mention: `vcgencmd measure_temp` reads the GPU temp (which also explains why the user has to be in the `video` group)  while `/sys/class/thermal/thermal_zone0/temp` is the CPU temp.

And yes, both valus would be nice, however I wasn't able to figure out why the `vcgencmd measure_temp` does not work when triggered remotely (locally, it works fine when running through sudo -u)

My readings:
```
root@pbx:~# echo $(( $(cat /sys/class/thermal/thermal_zone0/temp) / 1000 ))
36

root@pbx:~# /usr/bin/vcgencmd measure_temp
temp=35.0'C
```

**Comment by Napsty** [comment]
The readings are much closer now when I use the float method in the python script (not using the bash divide):

```
pi@raspberrypi:~ $ ./check_rpi_temp.py 
RPI TEMP OK: Temperature 24.60 degrees c |rpi_temp=24.60;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp2.py 
RPI TEMP OK: Temperature 24.64 degrees c |rpi_temp=24.64;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp.py 
RPI TEMP OK: Temperature 24.60 degrees c |rpi_temp=24.60;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp2.py 
RPI TEMP OK: Temperature 24.64 degrees c |rpi_temp=24.64;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp.py 
RPI TEMP OK: Temperature 24.60 degrees c |rpi_temp=24.60;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp2.py 
RPI TEMP OK: Temperature 25.18 degrees c |rpi_temp=25.18;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp.py 
RPI TEMP OK: Temperature 25.20 degrees c |rpi_temp=25.20;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp2.py 
RPI TEMP OK: Temperature 25.18 degrees c |rpi_temp=25.18;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp.py 
RPI TEMP OK: Temperature 24.60 degrees c |rpi_temp=24.60;0.00;0.00;;
pi@raspberrypi:~ $ ./check_rpi_temp2.py 
RPI TEMP OK: Temperature 24.64 degrees c |rpi_temp=24.64;0.00;0.00;;
```

So there's a very minor difference (second decimal) which is absolutely fine.

> Ah yes...I forgot to mention: vcgencmd measure_temp reads the GPU temp

Not sure about that, I think it reads the temperature from the board/SOC. But anyway, your PR looks good to me and the benefits are much better than the original way to find the temperature! Thanks!

**Review by Napsty — APPROVED** [review]

**Comment by sirtoobii** [comment]
> Not sure about that, I think it reads the temperature from the board/SOC. But anyway, your PR looks good to me and the benefits are much better than the original way to find the temperature! Thanks!

I agree with you. If you check the [official documentation](https://www.raspberrypi.org/documentation/raspbian/applications/vcgencmd.md) the lead text what the `vcgencmd` does it says:
> [...] is a command line utility that can get various pieces of information from the VideoCore GPU [...]

Then later where the `measure_temp` is introduced:
> Returns the temperature of the SoC as measured by the on-board temperature sensor.

Btw, the `get_throttled` seems interesting to monitor too...

Ah and thank you for merging my PR :)

**Pull request merged**
